# Generated by Django 5.2.3 on 2025-07-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contant',
            new_name='content',
        ),
    ]
