# Generated by Django 5.2.3 on 2025-07-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_about_skill_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
