# Generated by Django 5.2.3 on 2025-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_remove_about_title_remove_skill_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Без названия', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(default='default-icon', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='about_images/default.jpg', upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
