# Generated by Django 5.2.3 on 2025-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_home_remove_about_name_about_title_skill_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='фывапртоьбюююбьотрипмасвчсмитьб', max_length=200),
        ),
    ]
