# Generated by Django 5.2.3 on 2025-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Обо мне', max_length=200),
        ),
    ]
