# Generated by Django 5.2.3 on 2025-07-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_project_remove_home_created_at_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
