# Generated by Django 5.2.3 on 2025-07-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
