# Generated by Django 5.2.3 on 2025-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
