# Generated by Django 5.2.3 on 2025-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_education_about_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.RemoveField(
            model_name='about',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(default='Меня зовут Камрон', max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(default='Здравствуйте', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#7127BA', max_length=7),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
